#include <string>
typedef std::string str;
struct hd{ 
static const str s0;
static const str s1;
static const str s2;
static const str s3;
static const str s4;
static const str s5;
static const str s6;
static const str s7;
static const str s8;
static const str s9;
static const str s10;
static const str s11;
static const str s12;
static const str s13;
static const str s14;
static const str s15;
static const str s16;
static const str s17;
static const str s18;
static const str s19;
static const str s20;
static const str s21;
static const str s22;
static const str s23;
static const str s24;
static const str s25;
static const str s26;
static const str s27;
static const str s28;
static const str s29;
static const str s30;
static const str s31;
static const str s32;
static const str err_s1;
static const str err_s2;
static const str err_s3;
};


const str hd::s0="HTTP/1.1 200 OK\r\n";
const str hd::s1="Date: xxxxxxxxxxxxxxxxxxxxxxxx GMT\r\n";
const str hd::s2="Server: MATRIX\r\n";
const str hd::s3="Content-Type: %s; charset=utf-8\r\n";
const str hd::s4="Content-Length: %d \r\n";
const str hd::s5="Connection: keep-alive\r\n\r\n";
const str hd::s6="Connection: close\r\n\r\n";
const str hd::s7="HTTP/1.1";
const str hd::s8="Server: MATRIX\r\n";
const str hd::s9="Content-Type";
const str hd::s10="content-type";
const str hd::s11="Content-Length";
const str hd::s12="Connection";
const str hd::s13="Keep-Alive";
const str hd::s14="GET";
const str hd::s15="POST";
const str hd::s16="Host";
const str hd::s17="Date: ";
const str hd::s18="; charset=utf-8\r\n";
const str hd::s19=" GMT\r\n";
const str hd::s20="text/html";
const str hd::s21="text/javascript";
const str hd::s22="image/jpeg";
const str hd::s23="image/gif";
const str hd::s24="Accept:";
const str hd::s25="accept:";
const str hd::s26="connection";
const str hd::s27="content-length";
const str hd::s28="Content-Language";
const str hd::s29="content-language";
const str hd::s30="host";
const str hd::s31="\r\n\r\n";
const str hd::s32="close";
const str hd::err_s1="HTTP/1.1 404 Not Found\r\n";
const str hd::err_s2="HTTP/1.1 500 Internal Server Error\r\n";
const str hd::err_s3="HTTP/1.1 400 Bad Request\r\n";



